apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-04-04T06:24:11Z
  generation: 1
  labels:
    app: mm-grafana
    chart: grafana-0.8.5
    component: grafana
    heritage: Tiller
    release: mm
  name: mm-grafana
  namespace: default
  resourceVersion: "502289"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mm-grafana
  uid: c9ca1527-37d0-11e8-899f-005056a7d750
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-grafana
      component: grafana
      release: mm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: c754bd051d19fcaab42334d15a2d4e8dc75ed68e33ef310a339c972d0c9f4ba0
        checksum/dashboards-config: 406809e130d83dedf9868606e6f41e2052d7349e3c5ca1d14ac0d15a553623d5
      creationTimestamp: null
      labels:
        app: mm-grafana
        component: grafana
        release: mm
    spec:
      containers:
      - name: kubectl
        image: k8s.gcr.io/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
        imagePullPolicy: Always
        args: [
          "proxy", "-p", "8001"
        ]
      - env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: grafana-admin-user
              name: mm-grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: grafana-admin-password
              name: mm-grafana
        image: grafana/grafana:5.0.4
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/grafana
          name: config-volume
        - mountPath: /var/lib/grafana/dashboards
          name: dashboard-volume
        - mountPath: /var/lib/grafana
          name: storage-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - cp /tmp/config-volume-configmap/* /tmp/config-volume 2>/dev/null || true;
          cp /tmp/dashboard-volume-configmap/* /tmp/dashboard-volume 2>/dev/null ||
          true
        image: busybox
        imagePullPolicy: Always
        name: copy-configs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/config-volume-configmap
          name: config-volume-configmap
        - mountPath: /tmp/dashboard-volume-configmap
          name: dashboard-volume-configmap
        - mountPath: /tmp/config-volume
          name: config-volume
        - mountPath: /tmp/dashboard-volume
          name: dashboard-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 300
      volumes:
      - emptyDir: {}
        name: config-volume
      - emptyDir: {}
        name: dashboard-volume
      - configMap:
          defaultMode: 420
          name: mm-grafana-config
        name: config-volume-configmap
      - configMap:
          defaultMode: 420
          name: mm-grafana-dashs
        name: dashboard-volume-configmap
      - name: storage-volume
        persistentVolumeClaim:
          claimName: mm-grafana
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-04T06:24:11Z
    lastUpdateTime: 2018-04-04T06:24:11Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
